# Generated by Django 5.0.4 on 2024-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='api.tag'),
        ),
    ]
